# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'temp_rh_dashboard.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 100, 91, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 160, 131, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(230, 20, 341, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(30, 50, 741, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(250, 160, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(390, 80, 141, 21))
        self.label_5.setObjectName("label_5")
        self.radioButton_C = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_C.setGeometry(QtCore.QRect(390, 110, 71, 26))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_C.setFont(font)
        self.radioButton_C.setChecked(True)
        self.radioButton_C.setObjectName("radioButton_C")
        self.radioButton_F = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_F.setGeometry(QtCore.QRect(480, 110, 41, 26))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_F.setFont(font)
        self.radioButton_F.setObjectName("radioButton_F")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(50, 220, 211, 21))
        self.label_6.setObjectName("label_6")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(30, 270, 741, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(390, 320, 20, 251))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(310, 290, 171, 21))
        font = QtGui.QFont()
        font.setFamily("PibotoLt")
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.dial_temp = QtWidgets.QDial(self.centralwidget)
        self.dial_temp.setGeometry(QtCore.QRect(90, 340, 91, 101))
        self.dial_temp.setMaximum(50)
        self.dial_temp.setSliderPosition(0)
        self.dial_temp.setNotchesVisible(True)
        self.dial_temp.setObjectName("dial_temp")
        self.dial_rh = QtWidgets.QDial(self.centralwidget)
        self.dial_rh.setGeometry(QtCore.QRect(90, 460, 91, 101))
        self.dial_rh.setAutoFillBackground(False)
        self.dial_rh.setMaximum(100)
        self.dial_rh.setSliderPosition(0)
        self.dial_rh.setWrapping(False)
        self.dial_rh.setNotchesVisible(True)
        self.dial_rh.setObjectName("dial_rh")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(50, 320, 91, 21))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(50, 440, 131, 21))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(150, 320, 91, 21))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(180, 440, 91, 21))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(230, 320, 111, 21))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(260, 440, 91, 21))
        self.label_13.setObjectName("label_13")
        self.lcd_rh = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcd_rh.setGeometry(QtCore.QRect(630, 480, 64, 23))
        self.lcd_rh.setAutoFillBackground(False)
        self.lcd_rh.setStyleSheet("")
        self.lcd_rh.setFrameShape(QtWidgets.QFrame.Panel)
        self.lcd_rh.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcd_rh.setDigitCount(0)
        self.lcd_rh.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcd_rh.setObjectName("lcd_rh")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(530, 320, 121, 21))
        self.label_14.setObjectName("label_14")
        self.lcd_temp = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcd_temp.setGeometry(QtCore.QRect(630, 410, 64, 23))
        self.lcd_temp.setAutoFillBackground(False)
        self.lcd_temp.setStyleSheet("")
        self.lcd_temp.setFrameShape(QtWidgets.QFrame.Panel)
        self.lcd_temp.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcd_temp.setDigitCount(0)
        self.lcd_temp.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcd_temp.setObjectName("lcd_temp")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(420, 410, 141, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(420, 480, 181, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.pushButton_REFRESH = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_REFRESH.setGeometry(QtCore.QRect(400, 170, 101, 31))
        self.pushButton_REFRESH.setObjectName("pushButton_REFRESH")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(590, 150, 171, 21))
        self.label_17.setObjectName("label_17")
        self.text_refresh = QtWidgets.QTextEdit(self.centralwidget)
        self.text_refresh.setGeometry(QtCore.QRect(590, 180, 104, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_refresh.sizePolicy().hasHeightForWidth())
        self.text_refresh.setSizePolicy(sizePolicy)
        self.text_refresh.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.text_refresh.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.text_refresh.setObjectName("text_refresh")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(700, 190, 91, 21))
        self.label_18.setObjectName("label_18")
        self.pushButton_OK = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_OK.setGeometry(QtCore.QRect(640, 220, 51, 31))
        self.pushButton_OK.setObjectName("pushButton_OK")
        self.label_temp_dial = QtWidgets.QLabel(self.centralwidget)
        self.label_temp_dial.setGeometry(QtCore.QRect(250, 380, 21, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_temp_dial.setFont(font)
        self.label_temp_dial.setObjectName("label_temp_dial")
        self.label_rh_dial = QtWidgets.QLabel(self.centralwidget)
        self.label_rh_dial.setGeometry(QtCore.QRect(250, 500, 31, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_rh_dial.setFont(font)
        self.label_rh_dial.setObjectName("label_rh_dial")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(270, 380, 67, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(280, 500, 67, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.checkBox_yes = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_yes.setGeometry(QtCore.QRect(510, 350, 61, 26))
        self.checkBox_yes.setObjectName("checkBox_yes")
        self.checkBox_no = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_no.setGeometry(QtCore.QRect(610, 350, 51, 26))
        self.checkBox_no.setChecked(True)
        self.checkBox_no.setObjectName("checkBox_no")
        self.label_temp = QtWidgets.QLabel(self.centralwidget)
        self.label_temp.setGeometry(QtCore.QRect(200, 100, 67, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_temp.setFont(font)
        self.label_temp.setObjectName("label_temp")
        self.label_rh = QtWidgets.QLabel(self.centralwidget)
        self.label_rh.setGeometry(QtCore.QRect(200, 160, 41, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_rh.setFont(font)
        self.label_rh.setObjectName("label_rh")
        self.label_timestamp = QtWidgets.QLabel(self.centralwidget)
        self.label_timestamp.setGeometry(QtCore.QRect(270, 220, 171, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_timestamp.setFont(font)
        self.label_timestamp.setObjectName("label_timestamp")
        self.pushButton_PLOT = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_PLOT.setGeometry(QtCore.QRect(620, 90, 91, 31))
        self.pushButton_PLOT.setObjectName("pushButton_PLOT")
        #MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        #MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.dial_temp.valueChanged['int'].connect(self.label_temp_dial.setNum)
        self.dial_rh.valueChanged['int'].connect(self.label_rh_dial.setNum)
        self.checkBox_yes.clicked.connect(self.checkBox_no.toggle)
        self.checkBox_no.clicked.connect(self.checkBox_yes.toggle)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ECEN_5053 -- Project_1 -- Temp/RH monitor"))
        self.label.setText(_translate("MainWindow", "Temperature"))
        self.label_2.setText(_translate("MainWindow", "Relative Humidity"))
        self.label_3.setText(_translate("MainWindow", "Temperature and Relative Humidity Monitoring "))
        self.label_4.setText(_translate("MainWindow", "%"))
        self.label_5.setText(_translate("MainWindow", "Select display units"))
        self.radioButton_C.setText(_translate("MainWindow", "deg C"))
        self.radioButton_F.setText(_translate("MainWindow", "F"))
        self.label_6.setText(_translate("MainWindow", "Most Recent Data Fetched at"))
        self.label_7.setText(_translate("MainWindow", "Alarms and Indications"))
        self.label_8.setText(_translate("MainWindow", "Temperature"))
        self.label_9.setText(_translate("MainWindow", "Relative Humidity"))
        self.label_10.setText(_translate("MainWindow", "Threshold"))
        self.label_11.setText(_translate("MainWindow", "Threshold"))
        self.label_12.setText(_translate("MainWindow", "(0 to 50 deg C)"))
        self.label_13.setText(_translate("MainWindow", "(0 to 100 %)"))
        self.label_14.setText(_translate("MainWindow", "Activate Alarms?"))
        self.label_15.setText(_translate("MainWindow", "Temperature Alarm"))
        self.label_16.setText(_translate("MainWindow", "Relative Humidity Alarm"))
        self.pushButton_REFRESH.setText(_translate("MainWindow", "Refresh Data"))
        self.label_17.setText(_translate("MainWindow", "Set auto-refresh interval "))
        self.text_refresh.setPlaceholderText(_translate("MainWindow", "60"))
        self.label_18.setText(_translate("MainWindow", "seconds"))
        self.pushButton_OK.setText(_translate("MainWindow", "OK"))
        self.label_temp_dial.setText(_translate("MainWindow", "0"))
        self.label_rh_dial.setText(_translate("MainWindow", "0"))
        self.label_21.setText(_translate("MainWindow", "deg C"))
        self.label_22.setText(_translate("MainWindow", "%"))
        self.checkBox_yes.setText(_translate("MainWindow", "YES"))
        self.checkBox_no.setText(_translate("MainWindow", "NO"))
        self.label_temp.setText(_translate("MainWindow", "N/A"))
        self.label_rh.setText(_translate("MainWindow", "N/A"))
        self.label_timestamp.setText(_translate("MainWindow", "N/A"))
        self.pushButton_PLOT.setText(_translate("MainWindow", "Plot Data"))

